import React from 'react';
import './Main.css';


class Main extends React.Component {
    render() {
        return (
            <body>
            <div className='wrap'>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
                <div className='tri'></div>
            </div>
            <main className="main">
                <div className="container">
                <img src="./Bkg.jfif" className="bkg" alt="Snow"></img>
                        <div className="bottom-left"></div>
                        <div className="top-left"></div>
                        <div className="top-right"></div>
                        <div className="bottom-right"></div>
                        <div className="centered">
                        <img src="./ktjlogo.png" className="logo" alt="Snow"></img>   
                        <p data-content="Kshitij" className="text-link" style={{fontFamily: "cursive",fontSize:'3em',margin:0,padding:0 }} >Kshitij</p>
                        <p data-content="2020"  className="text-link" style={{fontFamily: "cursive",fontSize:'2em',margin:0,padding:0}}>2020</p>
                        <p data-content="Apocalyptic Adventure"  className="text-link" style={{ fontFamily: "cursive",fontSize:'4em',margin:0,padding:0}}>Apocalyptic Adventure</p>
                        </div>
                </div>
            </main>
            </body>
        )
    }
}

export default Main;